networks:
  247dink_api_shared:
    external: true

services:
  247d_ink:
    image: 247d_ink
    build:
      dockerfile: Dockerfile
      target: builder
    command: gow run main.go
    depends_on:
      - fs
    volumes:
      - ./server:/app:ro
    environment:
      - DINK247_SHARED_SECRET=339aba4a-d7c1-4b35-a8bd-d2ebb00fb258
      - FIRESTORE_PROJECT_ID=d-ink-4bf48
      - FIRESTORE_EMULATOR_HOST=fs:8080
    ports:
      - 8080:8080
    networks:
      - 247dink_api_shared

  fs:
    image: mtlynch/firestore-emulator-docker
    environment:
      - FIRESTORE_PROJECT_ID=d-ink-4bf48
    networks:
      - 247dink_api_shared
