name: Deploy
on: [pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        service_account: 'github@d-ink-4bf48.iam.gserviceaccount.com'
        workload_identity_provider: 'projects/238647978595/locations/global/workloadIdentityPools/github/providers/my-repo'

    - uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
      with:
        registry: us-central1-docker.pkg.dev
        project_id: d-ink-4bf48
        image_name: two47d-ink/247d.ink
        image_tag: latest
        dockerfile: ./Dockerfile
        context: ./

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'two47d-ink'
        image: 'us-central1-docker.pkg.dev/d-ink-4bf48/two47d-ink/247d.ink:latest'
        env_vars: |
          SHARED_SECRET=${{ secrets.SHARED_SECRET }}
          FIRESTORE_PROJECT_ID=d-ink-4bf48
          DEFAULT_REDIRECT=https://www.247dink.com/
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}

    - name: 'deployed at'
      run: 'curl "${{ steps.deploy.outputs.url }}"'

    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SECURITY_TOKEN }}'
        projectId: d-ink-4bf48
        channelId: live
